name: Python Executable

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA7: ${GITHUB_SHA::8}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag my-image-name:$(echo ${GITHUB_SHA} | cut -c1-7) .
