name: Python Executable

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }} 
        password: ${{ secrets.GHCR_TOKEN }}
        repository: karthikinala/github-actions-pg-helm
        tags: hello-world:$(echo ${GITHUB_SHA} | cut -c1-7) 
        run: docker build --file Dockerfile --tag hello-world:$(echo ${GITHUB_SHA} | cut -c1-7) .
